services:
  app-prod:
    build:
      context: .
      target: prod
    ports:
      - "${APP_PORT:-3000}:3000"
    volumes:
      - /app/node_modules
    working_dir: /app
    image: ${COMPOSE_PROJECT_NAME:-parking-front}:${IMAGE_TAG:-latest}
    environment:
      - NODE_ENV=production
    command: npm start